CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FullName" character varying(150) NOT NULL,
    "Email" character varying(255) NOT NULL,
    "PasswordHash" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

CREATE UNIQUE INDEX "IX_Users_Email" ON "Users" ("Email");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250824211549_CreateUserTableAndUniqueEmailIndex', '9.0.9');

CREATE TABLE "Analyses" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" character varying(200) NOT NULL,
    "Status" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "UserId" integer NOT NULL,
    CONSTRAINT "PK_Analyses" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Analyses_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Documents" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" character varying(200) NOT NULL,
    "FileName" character varying(500) NOT NULL,
    "Type" text NOT NULL,
    "Purpose" text NOT NULL,
    "FileSizeBytes" bigint NOT NULL,
    "MimeType" character varying(100),
    "ProcessingStatus" text NOT NULL,
    "ProcessingError" text,
    "ExtractedText" text,
    "IsChunked" boolean NOT NULL,
    "TotalChunks" integer NOT NULL,
    "Source" character varying(500),
    "CreatedAt" timestamp with time zone NOT NULL,
    "ProcessedAt" timestamp with time zone,
    "AnalysisId" integer NOT NULL,
    CONSTRAINT "PK_Documents" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Documents_Analyses_AnalysisId" FOREIGN KEY ("AnalysisId") REFERENCES "Analyses" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Questions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Text" character varying(1000) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "AnalysisId" integer NOT NULL,
    CONSTRAINT "PK_Questions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Questions_Analyses_AnalysisId" FOREIGN KEY ("AnalysisId") REFERENCES "Analyses" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Stages" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(100) NOT NULL,
    "Description" character varying(500),
    "Order" integer NOT NULL,
    "PartialResult" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "AnalysisId" integer NOT NULL,
    "StageType" character varying(21) NOT NULL,
    CONSTRAINT "PK_Stages" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Stages_Analyses_AnalysisId" FOREIGN KEY ("AnalysisId") REFERENCES "Analyses" ("Id") ON DELETE CASCADE
);

CREATE TABLE "DocumentChunks" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "DocumentId" integer NOT NULL,
    "ChunkIndex" integer NOT NULL,
    "Content" text NOT NULL,
    "StartPosition" integer NOT NULL,
    "EndPosition" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_DocumentChunks" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_DocumentChunks_Documents_DocumentId" FOREIGN KEY ("DocumentId") REFERENCES "Documents" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Analyses_CreatedAt" ON "Analyses" ("CreatedAt");

CREATE INDEX "IX_Analyses_UserId" ON "Analyses" ("UserId");

CREATE UNIQUE INDEX "IX_DocumentChunks_DocumentId_ChunkIndex" ON "DocumentChunks" ("DocumentId", "ChunkIndex");

CREATE INDEX "IX_Documents_AnalysisId" ON "Documents" ("AnalysisId");

CREATE INDEX "IX_Questions_AnalysisId" ON "Questions" ("AnalysisId");

CREATE INDEX "IX_Stages_AnalysisId" ON "Stages" ("AnalysisId");

CREATE INDEX "IX_Stages_AnalysisId_Order" ON "Stages" ("AnalysisId", "Order");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250913232331_DocumentsAndAnalysis', '9.0.9');

DROP TABLE "DocumentChunks";

ALTER TABLE "Documents" DROP COLUMN "ExtractedText";

ALTER TABLE "Documents" DROP COLUMN "FileSizeBytes";

ALTER TABLE "Documents" DROP COLUMN "IsChunked";

ALTER TABLE "Documents" DROP COLUMN "MimeType";

ALTER TABLE "Documents" DROP COLUMN "ProcessedAt";

ALTER TABLE "Documents" DROP COLUMN "ProcessingStatus";

ALTER TABLE "Documents" DROP COLUMN "TotalChunks";

ALTER TABLE "Documents" RENAME COLUMN "Type" TO "FileType";

ALTER TABLE "Documents" RENAME COLUMN "ProcessingError" TO "Content";

ALTER TABLE "Documents" ADD "FileData" bytea NOT NULL DEFAULT BYTEA E'\\x';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250914004937_RefactorDocument', '9.0.9');

ALTER TABLE "Documents" DROP COLUMN "FileData";

ALTER TABLE "Documents" ADD "FilePath" text NOT NULL DEFAULT '';

ALTER TABLE "Documents" ADD "FileSize" bigint NOT NULL DEFAULT 0;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250917001805_AddDocumentColumns', '9.0.9');

CREATE EXTENSION IF NOT EXISTS vector;

ALTER TABLE "Documents" ALTER COLUMN "FilePath" TYPE character varying(1000);

CREATE TABLE "Chunks" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "DocumentId" integer NOT NULL,
    "ChunkIndex" integer NOT NULL,
    "Content" character varying(10000) NOT NULL,
    "Embedding" vector(768) NOT NULL,
    "Metadata" jsonb NOT NULL,
    "TokenCount" integer NOT NULL,
    "StartPosition" integer NOT NULL,
    "EndPosition" integer NOT NULL,
    CONSTRAINT "PK_Chunks" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Chunks_Documents_DocumentId" FOREIGN KEY ("DocumentId") REFERENCES "Documents" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Chunks_DocumentId" ON "Chunks" ("DocumentId");

CREATE INDEX "IX_Chunks_DocumentId_ChunkIndex" ON "Chunks" ("DocumentId", "ChunkIndex");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250928220756_AddChunksTable', '9.0.9');

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251004230734_EnablePgvectorExtension', '9.0.9');

DROP TABLE "Questions";

ALTER TABLE "Analyses" ADD "Question" text NOT NULL DEFAULT '';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251012015439_RemoveQuestions', '9.0.9');

DROP INDEX "IX_Stages_AnalysisId_Order";

ALTER TABLE "Stages" DROP COLUMN "Order";

ALTER TABLE "Stages" DROP COLUMN "PartialResult";

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251018230153_RemoveUnecessaryColumnsEntityStage', '9.0.9');

ALTER TABLE "Stages" DROP COLUMN "Description";

ALTER TABLE "Stages" DROP COLUMN "Name";

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251018231115_RemoveUnecessaryColumsEntityStage', '9.0.9');

ALTER TABLE "Documents" ADD "GcsFilePath" text NOT NULL DEFAULT '';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251023235922_AddGcsPathDocument', '9.0.9');

CREATE TABLE "Indicators" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(100) NOT NULL,
    CONSTRAINT "PK_Indicators" PRIMARY KEY ("Id")
);

CREATE TABLE "Indexes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(100) NOT NULL,
    "Description" character varying(500),
    "IndicatorId" integer NOT NULL,
    "PreAnalysisStageId" integer NOT NULL,
    CONSTRAINT "PK_Indexes" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Indexes_Indicators_IndicatorId" FOREIGN KEY ("IndicatorId") REFERENCES "Indicators" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Indexes_Stages_PreAnalysisStageId" FOREIGN KEY ("PreAnalysisStageId") REFERENCES "Stages" ("Id") ON DELETE CASCADE
);

CREATE TABLE "IndexReferences" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "IndexId" integer NOT NULL,
    "SourceDocumentUri" text NOT NULL,
    "Page" text NOT NULL,
    "Line" text NOT NULL,
    "QuotedContent" text,
    CONSTRAINT "PK_IndexReferences" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_IndexReferences_Indexes_IndexId" FOREIGN KEY ("IndexId") REFERENCES "Indexes" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Indexes_IndicatorId" ON "Indexes" ("IndicatorId");

CREATE UNIQUE INDEX "IX_Indexes_PreAnalysisStageId_Name" ON "Indexes" ("PreAnalysisStageId", "Name");

CREATE INDEX "IX_IndexReferences_IndexId" ON "IndexReferences" ("IndexId");

CREATE UNIQUE INDEX "IX_Indicators_Name" ON "Indicators" ("Name");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251024033344_AddIndexesAndRelatesModels', '9.0.9');

ALTER TABLE "Indicators" ALTER COLUMN "Name" TYPE character varying(1000);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251024154154_UpdateIndicatorNameLength', '9.0.9');

ALTER TABLE "Analyses" ALTER COLUMN "Question" DROP NOT NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251024225639_RemoveRequiredQuestionAnalysis', '9.0.9');

CREATE TABLE "Categories" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(200) NOT NULL,
    "Definition" character varying(1000) NOT NULL,
    "Frequency" integer NOT NULL,
    "ExplorationOfMaterialStageId" integer NOT NULL,
    CONSTRAINT "PK_Categories" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Categories_Stages_ExplorationOfMaterialStageId" FOREIGN KEY ("ExplorationOfMaterialStageId") REFERENCES "Stages" ("Id") ON DELETE CASCADE
);

CREATE TABLE "RegisterUnits" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Text" text NOT NULL,
    "SourceDocumentUri" character varying(1000) NOT NULL,
    "Page" character varying(20) NOT NULL,
    "Line" character varying(20) NOT NULL,
    "Justification" character varying(1000) NOT NULL,
    "CategoryId" integer NOT NULL,
    CONSTRAINT "PK_RegisterUnits" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RegisterUnits_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "Categories" ("Id") ON DELETE CASCADE
);

CREATE TABLE "IndexRegisterUnit" (
    "FoundIndicesId" integer NOT NULL,
    "RegisterUnitsId" integer NOT NULL,
    CONSTRAINT "PK_IndexRegisterUnit" PRIMARY KEY ("FoundIndicesId", "RegisterUnitsId"),
    CONSTRAINT "FK_IndexRegisterUnit_Indexes_FoundIndicesId" FOREIGN KEY ("FoundIndicesId") REFERENCES "Indexes" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_IndexRegisterUnit_RegisterUnits_RegisterUnitsId" FOREIGN KEY ("RegisterUnitsId") REFERENCES "RegisterUnits" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX "IX_Categories_ExplorationOfMaterialStageId_Name" ON "Categories" ("ExplorationOfMaterialStageId", "Name");

CREATE INDEX "IX_IndexRegisterUnit_RegisterUnitsId" ON "IndexRegisterUnit" ("RegisterUnitsId");

CREATE INDEX "IX_RegisterUnits_CategoryId" ON "RegisterUnits" ("CategoryId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251025224928_AddExplorationStageEntities', '9.0.9');

ALTER TABLE "Users" ALTER COLUMN "FullName" TYPE character varying(80);

ALTER TABLE "Users" ALTER COLUMN "Email" TYPE character varying(100);

ALTER TABLE "Indexes" ALTER COLUMN "Name" TYPE character varying(500);

ALTER TABLE "Analyses" ALTER COLUMN "Title" TYPE character varying(100);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251102211302_UpdateMaxCaracteresIndexName', '9.0.9');

ALTER TABLE "Indexes" ALTER COLUMN "Description" TYPE character varying(1000);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251102211628_UpdateMaxCaracteresIndexDescription', '9.0.9');

ALTER TABLE "RegisterUnits" DROP COLUMN "Line";

ALTER TABLE "IndexReferences" DROP COLUMN "Line";

UPDATE "IndexReferences" SET "QuotedContent" = '' WHERE "QuotedContent" IS NULL;
ALTER TABLE "IndexReferences" ALTER COLUMN "QuotedContent" SET NOT NULL;
ALTER TABLE "IndexReferences" ALTER COLUMN "QuotedContent" SET DEFAULT '';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251109012342_AddQuotedContentRemoveLine', '9.0.9');

COMMIT;

